#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# get parameters from git-cz push
echo "HUSKY_GIT_PARAMS: $HUSKY_GIT_PARAMS"
echo "@ $@";
echo "1: $1";
echo "2: $2";
echo "3: $3";
echo "4: $4";
echo "5: $5";

exit 1;