#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Set --follow-tags in pre-push hook
# This is useful for GitHub Actions
# See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#using-environment-variables-in-the-action
if [ "$HUSKY_GIT_PARAMS" = "" ]; then
  export HUSKY_GIT_PARAMS="--follow-tags"
fi

echo "HUSKY_GIT_PARAMS: $HUSKY_GIT_PARAMS"